name: ethic
recipe: lamp
services:
  node:
    type: node:14
    globals:
      gulp-cli: latest
      yarn: latest
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
